const SCAN_LIMIT = 500_000;
const CHALLENGE_SCAN_LIMIT = 200_000;

const SPA_MARKERS = [
  'id="root"',
  'id="app"',
  'id="__next"',
  'id="__nuxt"',
  'id="__gatsby"',
  'id="svelte"',
  "ng-app",
  "data-reactroot",
  "data-reactid",
  "data-remix-run",
  "data-sveltekit",
  "data-astro-",
  "__next_data__",
  "__nuxt__",
  "__sveltekit_data",
  "gatsby-focus-wrapper",
  'id="storybook-root"',
  'id="storybook-docs"',
];

const CHALLENGE_PHRASES = [
  "performing security verification",
  "verify you are human",
  "checking your browser",
  "enable javascript and cookies",
  "the request could not be satisfied",
  "generated by cloudfront",
  "configured to block access",
];

const VENDOR_MARKERS: ReadonlyArray<readonly [string, string]> = [
  ["cloudflare", "cf-browser-verification"],
  ["cloudflare", "cf-challenge-running"],
  ["cloudflare", "challenge-platform/h/"],
  ["cloudflare", "_cf_chl_opt"],
  ["perimeterx", "captcha.px-cdn.net"],
  ["datadome", "captcha-delivery.com"],
  ["imperva", "_incapsula_resource"],
  ["sucuri", "sucuri website firewall"],
  ["kasada", "kpsdk.scriptstart = kpsdk.now()"],
];

export type RenderReason =
  | "bot-challenge"
  | "client-redirect"
  | "javascript-required"
  | "loading-placeholder"
  | "spa-shell"
  | "thin-scripted";

export type RenderDecision =
  | {
      render: false;
      visibleTextLength: number;
    }
  | {
      render: true;
      reason: RenderReason;
      visibleTextLength: number;
      vendor?: string;
    };

export interface DetectRenderOptions {
  contentType?: string;
  statusCode?: number;
}

// detects whether a given HTML document requires rendering in a browser to be properly processed. This function analyzes the HTML content and its characteristics to determine if it is likely to be a bot challenge, a client-side redirect, or if it requires JavaScript execution to display meaningful content. It also checks for single-page application (SPA) markers and loading placeholders that may indicate the need for rendering.
export function detectRenderNeed(html: string, options: DetectRenderOptions = {}): RenderDecision {
  if (!isHtmlContentType(options.contentType) || options.statusCode === 204) {
    return { render: false, visibleTextLength: 0 };
  }

  // Bound policy work because detection runs on every successful HTTP response.
  const scanned = html.slice(0, SCAN_LIMIT).toLowerCase();
  const bodyHtml = extractBody(scanned, html.length > SCAN_LIMIT);
  const visibleText = extractVisibleText(bodyHtml);
  const visibleTextLength = countNonWhitespace(visibleText);

  const vendor = detectChallengeVendor(scanned);
  if (vendor || isGenericChallenge(visibleText, html.length)) {
    return {
      render: true,
      reason: "bot-challenge",
      visibleTextLength,
      ...(vendor ? { vendor } : {}),
    };
  }

  if (hasClientRedirect(scanned)) {
    return { render: true, reason: "client-redirect", visibleTextLength };
  }

  if (visibleTextLength < 500 && requiresJavaScript(visibleText, scanned)) {
    return { render: true, reason: "javascript-required", visibleTextLength };
  }

  if (visibleTextLength < 200 && SPA_MARKERS.some((marker) => scanned.includes(marker))) {
    return { render: true, reason: "spa-shell", visibleTextLength };
  }

  const executableScriptCount = countExecutableScripts(scanned);
  if (
    (visibleTextLength < 200 && executableScriptCount > 0) ||
    (visibleTextLength < 1000 && executableScriptCount >= 5)
  ) {
    return { render: true, reason: "thin-scripted", visibleTextLength };
  }

  if (visibleTextLength < 400 && looksLikeLoadingPlaceholder(visibleText, bodyHtml)) {
    return { render: true, reason: "loading-placeholder", visibleTextLength };
  }

  return { render: false, visibleTextLength };
}

// hasClientRedirect checks if the HTML contains a meta refresh tag that redirects to another URL. It looks for <meta> tags with http-equiv="refresh" and a URL specified in the content attribute.? why is it looking for meta refresh tags? Because they can be used to redirect users to another page, which may require rendering to follow the redirect and obtain the final content.
export function hasClientRedirect(html: string): boolean {
  const lower = html.toLowerCase();
  for (const fragment of lower.split("<meta").slice(1)) {
    const tag = fragment.split(">", 1)[0] ?? "";
    if (tag.includes("http-equiv") && tag.includes("refresh") && tag.includes("url=")) {
      return true;
    }
  }
  return false;
}

// why is this function counting executable scripts? Because the presence of executable scripts may indicate that the page relies on JavaScript for rendering content, which may require rendering in a browser to obtain the final content.
export function countExecutableScripts(html: string): number {
  const lower = html.toLowerCase();
  let count = 0;

  for (const fragment of lower.split("<script").slice(1)) {
    const [tag = "", remainder = ""] = fragment.split(">", 2);
    const dataOnly =
      tag.includes("application/json") ||
      tag.includes("application/ld+json") ||
      tag.includes("importmap") ||
      tag.includes("speculationrules");

    if (dataOnly) continue;
    if (tag.includes("src=")) {
      count += 1;
      continue;
    }

    const inline = remainder.split("</script>", 1)[0] ?? "";
    if (inline.trim().length > 8) count += 1;
  }

  return count;
}

function isHtmlContentType(contentType?: string): boolean {
  if (!contentType) return true;
  const mime = contentType.split(";", 1)[0]?.trim().toLowerCase();
  return mime === "text/html" || mime === "application/xhtml+xml";
}

function requiresJavaScript(visibleText: string, html: string): boolean {
  return (
    visibleText.includes("enable javascript") ||
    visibleText.includes("javascript is required") ||
    (html.includes("<noscript") && visibleText.includes("javascript"))
  );
}

function detectChallengeVendor(html: string): string | undefined {
  const head = html.slice(0, CHALLENGE_SCAN_LIMIT);
  return VENDOR_MARKERS.find(([, marker]) => head.includes(marker))?.[0];
}

function isGenericChallenge(visibleText: string, htmlLength: number): boolean {
  if (htmlLength > 80_000 || countNonWhitespace(visibleText) > 600) return false;
  return CHALLENGE_PHRASES.some((phrase) => visibleText.includes(phrase));
}

function looksLikeLoadingPlaceholder(visibleText: string, bodyHtml: string): boolean {
  const loadingText = [
    "loading...",
    "loading…",
    "please wait",
    "just a moment",
    "initializing",
    "preparing",
    "one moment",
  ];
  if (loadingText.some((marker) => visibleText.includes(marker))) return true;

  if (countNonWhitespace(visibleText) >= 200) return false;
  const domMarkers = [
    'class="spinner',
    'class="loader',
    'class="loading',
    'class="preloader',
    'id="loader',
    'id="preloader',
    'aria-label="loading"',
  ];
  return domMarkers.some((marker) => bodyHtml.includes(marker));
}

function extractBody(html: string, scanWasTruncated: boolean): string {
  const bodyOpen = html.indexOf("<body");
  if (bodyOpen < 0) return "";

  const contentStart = html.indexOf(">", bodyOpen);
  if (contentStart < 0) return "";

  const bodyClose = html.lastIndexOf("</body>");
  if (bodyClose < 0 && !scanWasTruncated) return "";
  const contentEnd = bodyClose >= 0 ? bodyClose : html.length;
  if (contentStart >= contentEnd) return "";

  return stripTagBlock(stripTagBlock(html.slice(contentStart + 1, contentEnd), "script"), "style");
}

function stripTagBlock(html: string, tag: string): string {
  const opening = `<${tag}`;
  const closing = `</${tag}>`;
  let remaining = html;
  let result = "";

  while (true) {
    const start = remaining.indexOf(opening);
    if (start < 0) return result + remaining;
    result += remaining.slice(0, start);

    const end = remaining.indexOf(closing, start);
    if (end < 0) return result;
    remaining = remaining.slice(end + closing.length);
  }
}

function extractVisibleText(html: string): string {
  let text = "";
  let insideTag = false;
  let previousWasWhitespace = true;

  for (const character of html) {
    if (character === "<") {
      insideTag = true;
    } else if (character === ">") {
      insideTag = false;
    } else if (!insideTag) {
      if (/\s/.test(character)) {
        if (!previousWasWhitespace) text += " ";
        previousWasWhitespace = true;
      } else {
        text += character;
        previousWasWhitespace = false;
      }
    }
  }

  return text.trim();
}

function countNonWhitespace(value: string): number {
  let count = 0;
  for (const character of value) {
    if (!/\s/.test(character)) count += 1;
  }
  return count;
}
